#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR
pwd

echo "Building raurman..."
if cargo build --release ; then
  echo "Build complete!"
  echo "Installing..."
  if sudo mv target/release/raurman /usr/bin/. ; then
    echo "Installation complete!"
  else
    echo "Installation failed!"
  fi
fi
